### ISSUE TITLE
High CPU usage on RPi4

### ISSUE THREAD

**Issue by klara31** [Mictronics/readsb-protobuf#14] opened 2021-01-09 09:56 UTC
I have also reported this under https://github.com/mikenye/docker-readsb-protobuf/issues/17.

I am using readsb-protobuf on a Raspberry Pi 4 (4Gb), using the docker container mikenye/readsb-protobuf:latest. Readsb is continuously using up one CPU core completely. As far as I recall, this only happened since a couple of days, performance statistics also show an increase.

Is this normal behavior and if not: do you have a clue what's causing this?

**Comment by mikenye** [comment] 2021-01-09 09:58
@Mictronics happy to work with you on this one - just let me know what I can do to help.

**Comment by BugDeliverer** [comment] 2021-04-05 19:59
I have the same problem on my Raspberry Pi 3 running Arch Linux Arm...

**Comment by Mictronics** [comment] 2021-04-06 13:11
I have no glue about Docker and that stuff so can't tell how things work inside a container. But we never had any reports of such issues for installations outside containers, meaning readsb running on a host OS.
I doubt you run a GNS Hulc antenna with readsb. There was a bug fix that caused a high CPU usage due to fragmented messages.

What is your overall hardware setup?

**Comment by BugDeliverer** [comment] 2021-04-06 16:40
Unfortunately I'm also not a docker expert, but as far as I know that shouldn't make any difference.
My hardware setup pritty simple:
- Raspberry Pi 3 Model B+ 
- original Raspberry 2.5A power supply
- FlightAware Pro Stick Plus
- groundplane antenna

As already mentioned running Arch Linux Arm (32bit) with all updates applied, means among others
- Kernel: Linux 5.10.25-5-ARCH armv7l
- Docker: 20.10.5-1
- Container: mikenye/docker-readsb-protobuf:latest (with example config from its github)

**Update:**
Played around a little bit. In his example-configuration mikenye sets READSB_DCFILTER=true. He mentions that it is a 1Hz DC filter and that it uses more cpu. After deactivation cpu usage drops to approximately 30% (SDR Reader was 30% now is 7%); Demodulator increases from 15-20% to 25%).
What are usual values on a Raspberry Pi 3B+, with and without DCFILTER and what is it good for?

**Comment by Mictronics** [comment] 2021-05-21 09:58
DCFILTER is for removing a DC offset in IQ data caused by the SDR internal AD converter. Not sure if that option is ever used.

I close this issue since the primary one in https://github.com/mikenye/docker-readsb-protobuf/issues/17 is closed too.

**Closed as completed by Mictronics** 2021-05-21 09:58 UTC
