### ISSUE TITLE
new DB versioning scheme?

### ISSUE THREAD

**Issue by kx1t** [Mictronics/readsb-protobuf#23] opened 2023-04-28 19:29 UTC
The aircraft db version went from version 344 to version 16 in this commit: https://github.com/Mictronics/readsb-protobuf/commit/3254ac74c18c1f077fb8112ef89015a26ca48c23

This is throwing off some of the deployments we have where it looks like the new DB is not compatible with the old one?  This is what is shown in a pop-up in the webapp:
![image](https://user-images.githubusercontent.com/15090643/235235383-8ad7f59a-9313-4958-a75c-c6ef13f732b9.png)

When I went back through history, it appears that this happened in the past as well -- here it went wrong https://github.com/Mictronics/readsb-protobuf/commit/1a5f682ed9cfe5b082901a8f03e0c317c6acc93f and here it got fixed again: https://github.com/Mictronics/readsb-protobuf/commit/593d23115dff233b8f638b54e2c808ca6572b2b9

thanks!

**Comment by Mictronics** [comment] 2023-05-06 03:06
Thanks for reporting. Will be fixed with next update. Caused by creating new database in a temporary environment.

**Closed as completed by Mictronics** 2023-05-06 03:06 UTC
